#lane_control/lane_controller_node

lookahead_distance: 0.12
max_lookahead_distance: 1.0
max_forward: 0.6
kp_steering: 4.5

v_bar: 0.25
v_max: 2.5
# v_bar: 2.5
width: 0.1
omega_factor: 60.0

# TODO: lane filter should publish this information
d_resolution: 0.011
phi_resolution: 0.051

stop_line_slowdown:
  start: 0.4
  end: 0.1

verbose: 0
